apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ezswitch-controller
  name: zesty-ezswitch-ezswitch-controller
  namespace: '{{ .Release.Namespace }}'
